language: go

go:
  - 1.2

install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get labix.org/v2/mgo
  - go get github.com/miekg/dns
  - go get code.google.com/p/go.net/idna

before_script:
  - npm install karma
  - npm install karma-jasmine
  - npm install karma-firefox-launcher
  - npm install karma-ng-html2js-preprocessor
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - ./test-all.sh

notifications:
  email:
    recipients:
      - rafael@justo.net.br
    on_success: change
    on_failure: always

services:
  - mongodb
