language: go

go:
  - 1.3

env:
  # "gvm update" resets GOOS and GOARCH environment variable, workaround it by setting
  # BUILD_GOOS and BUILD_GOARCH and overriding GOARCH and GOOS in the build script
  global:
    - BUILD_GOARCH=amd64
  matrix:
    - BUILD_GOOS=linux
    - BUILD_GOOS=darwin
    - BUILD_GOOS=windows

install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get gopkg.in/mgo.v2
  - go get github.com/miekg/dns
  - go get code.google.com/p/go.net/idna
  - go get github.com/rafaeljusto/handy

before_script:
  - npm install karma
  - npm install karma-jasmine
  - npm install karma-phantomjs-launcher
  - npm install karma-ng-html2js-preprocessor
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - gvm cross $BUILD_GOOS $BUILD_GOARCH
  - GOARCH=$BUILD_GOARCH GOOS=$BUILD_GOOS go build

  # only test on linux
  - if [ $BUILD_GOOS == "linux" ]; then GOARCH=$BUILD_GOARCH GOOS=$BUILD_GOOS ./test-all.sh; fi

notifications:
  email:
    recipients:
      - rafael@justo.net.br
    on_success: change
    on_failure: always

services:
  - mongodb
