language: go

go:
  - tip

env:
  # "gvm update" resets GOOS and GOARCH environment variable, workaround it by setting
  # BUILD_GOOS and BUILD_GOARCH and overriding GOARCH and GOOS in the build script
  global:
    - BUILD_GOARCH=amd64
  matrix:
    - BUILD_GOOS=linux
    - BUILD_GOOS=darwin
    - BUILD_GOOS=windows

install:
  - go get code.google.com/p/go.tools/cmd/cover

before_script:
  - npm install karma
  - npm install karma-jasmine
  - npm install karma-phantomjs-launcher
  - npm install karma-ng-html2js-preprocessor
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - gvm cross $BUILD_GOOS $BUILD_GOARCH
  - GOARCH=$BUILD_GOARCH GOOS=$BUILD_GOOS go build

  # only test on linux
  - if [ $BUILD_GOOS == "linux" ]; then GOARCH=$BUILD_GOARCH GOOS=$BUILD_GOOS ./test-all.sh; fi

notifications:
  email:
    recipients:
      - rafael@justo.net.br
    on_success: change
    on_failure: always

# For now on we are only testing the unit and interface layers in Travis. Because are tests takes
# too long and consume resources that Travis don't have. The full test will be performed by the
# integration tool.

#services:
#  - mongodb
